title: Martin Diaz-Valdes # your name (or website title) here
logo: "/images/MartinPortImage.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst | Insights | Stories | People 
  <br><br>
  Thanks for checking out my portfolio page! I am a Data Analyst with 5+ years experience in the People and Talent Domain. 
  I'm looking for my next opportunity with a innovative company, looking for their next Data Analyst. I'm open to several industries, but have a passion for
  People, Healthcare, Products, & Gaming/Entertainment. Feel free to reach out!
  <br><br>
  <a href="https://www.linkedin.com/in/martdv/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
